apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "15s"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "30s"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "30s"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - abc.fevirtus.dev
      secretName: ingress-cert
  rules:
    - host: abc.fevirtus.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-svc
                port:
                  number: 80
